/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAAAAA: typeof import('./src/components/AAAAAA.vue')['default']
    BackgroundGrid: typeof import('./src/components/backgrounds/BackgroundGrid.vue')['default']
    BackgroundTrees: typeof import('./src/components/backgrounds/backgroundTrees.vue')['default']
    ButtonSecondary: typeof import('./src/components/buttons/ButtonSecondary.vue')['default']
    ContentPanel: typeof import('./src/components/ContentPanel.vue')['default']
    DocsMarkdown: typeof import('./src/components/DocsMarkdown.vue')['default']
    FooterBar: typeof import('./src/components/FooterBar.vue')['default']
    GameTitle: typeof import('./src/components/GameTitle.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InlineIcon: typeof import('./src/components/InlineIcon.vue')['default']
    LogoGN: typeof import('./src/components/LogoGN.vue')['default']
    MarkdownPage: typeof import('./src/components/MarkdownPage.vue')['default']
    ModeToggle: typeof import('./src/components/ModeToggle.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    PanelWarning: typeof import('./src/components/panels/PanelWarning.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmartLink: typeof import('./src/components/utils/SmartLink.vue')['default']
    TExt: typeof import('./src/components/labels/TExt.vue')['default']
    TextRandom: typeof import('./src/components/TextRandom.vue')['default']
    ThumbnailButton: typeof import('./src/components/buttons/ThumbnailButton.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
